### ISSUE TITLE
UnexpectedValueException by binary file response cache

### ISSUE THREAD

**Issue by ktanakaj** [spatie/laravel-responsecache#179]
Hi! I try to use laravel-responsecache for my APIs.
I confirmed laravel-responsecache working with JSON API.
But I got `UnexpectedValueException` with binary API that respond an image file from DB blob column.
Can't I use `laravel-responsecache` for binary file API?

The stack trace is following.
```
UnexpectedValueException: The Response content must be a string or object implementing __toString(), "boolean" given. in /vagrant/server/vendor/symfony/http-foundation/Response.php:401
Stack trace:
#0 /vagrant/server/vendor/symfony/http-foundation/Response.php(202): Symfony\Component\HttpFoundation\Response->setContent(false)
#1 /vagrant/server/vendor/spatie/laravel-responsecache/src/ResponseSerializer.php(76): Symfony\Component\HttpFoundation\Response->__construct(false, 200)
#2 /vagrant/server/vendor/spatie/laravel-responsecache/src/ResponseSerializer.php(27): Spatie\ResponseCache\ResponseSerializer->buildResponse(Array)
#3 /vagrant/server/vendor/spatie/laravel-responsecache/src/ResponseCacheRepository.php(39): Spatie\ResponseCache\ResponseSerializer->unserialize('a:4:{s:10:"stat...')
#4 /vagrant/server/vendor/spatie/laravel-responsecache/src/ResponseCache.php(69): Spatie\ResponseCache\ResponseCacheRepository->get('responsecache-5...')
#5 /vagrant/server/vendor/spatie/laravel-responsecache/src/Middlewares/CacheResponse.php(28): Spatie\ResponseCache\ResponseCache->getCachedResponseFor(Object(Illuminate\Http\Request))
#6 /vagrant/server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Spatie\ResponseCache\Middlewares\CacheResponse->handle(Object(Illuminate\Http\Request), Object(Closure), '120')
#7 /vagrant/server/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /vagrant/server/vendor/laravel/framework/src/Illuminate/Http/Middleware/SetCacheHeaders.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /vagrant/server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Http\Middleware\SetCacheHeaders->handle(Object(Illuminate\Http\Request), Object(Closure), 'public')
#10 /vagrant/server/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /vagrant/server/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(58): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /vagrant/server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), 120, '1')
#13 /vagrant/server/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /vagrant/server/app/Http/Middleware/SetRequestTime.php(36): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /vagrant/server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\Http\Middleware\SetRequestTime->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /vagrant/server/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /vagrant/server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /vagrant/server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /vagrant/server/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /vagrant/server/vendor/barryvdh/laravel-cors/src/HandleCors.php(36): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /vagrant/server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /vagrant/server/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /vagrant/server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /vagrant/server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 /vagrant/server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 /vagrant/server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#27 /vagrant/server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#28 /vagrant/server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#29 /vagrant/server/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#30 /vagrant/server/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /vagrant/server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /vagrant/server/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /vagrant/server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /vagrant/server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /vagrant/server/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /vagrant/server/app/Http/Middleware/AccessLog.php(23): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /vagrant/server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\Http\Middleware\AccessLog->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /vagrant/server/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /vagrant/server/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /vagrant/server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Barryvdh\Cors\HandlePreflight->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /vagrant/server/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /vagrant/server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 /vagrant/server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#44 /vagrant/server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#45 /vagrant/server/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#46 {main}
```

**Comment by ktanakaj** [comment]
Please let me add this information.
I used `streamDownload` method to respond an image file like following.

```
public function image(int $id)
{
    $content = ImageContent::findOrFail($id);
    $headers = [
        'Content-Type' => $content->mimetype,
        'Cache-Control' => 'public',
    ];
    $body = $content->body;
    return response()->streamDownload(function () use ($body) {
        echo $body;
    }, null, $headers);
}
```

**Comment by freekmurze** [comment]
The package does not cache binary responses right now. If this can be added easily I'd accept a PR with tests that adds this.
